src/forum_modules/exporter/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import state, running, download

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('state/')),  state, name='exporter_state'),
    url(r'^%s(?P<mode>\w+)/%s$' % (_('admin/'), _('running/')),  running, name='exporter_running'),
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('download/')),  download, name='exporter_download'),
)

src/forum_modules/facebookauth/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from views import user_is_registered

urlpatterns = patterns('',
    url(r'^xd_receiver.htm$',  direct_to_template,  {'template': 'modules/facebookauth/xd_receiver.html'}, name='xd_receiver'),
    url(r'^facebook/user_is_registered/', user_is_registered, name="facebook_user_is_registered"),
)

src/forum_modules/robotstxt/urls.py
from django.conf.urls.defaults import *
from django.http import  HttpResponse
import settings

urlpatterns = patterns('',
    (r'^robots.txt$',  lambda r: HttpResponse(settings.ROBOTS_FILE.value)),
)

src/urls.py
from django.conf.urls.defaults import *
from django.utils.translation import ugettext as _
from django.conf import settings

urlpatterns = patterns('',
    (r'', include('forum.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

handler404 = 'forum.views.meta.page'
handler500 = 'forum.views.meta.error_handler'

src/forum/models/tag.py
import datetime
from base import *

from django.utils.translation import ugettext as _

from forum import modules

class ActiveTagManager(models.Manager):
    def get_query_set(self):
        return super(ActiveTagManager, self).get_query_set().exclude(used_count__lt=1)

class Tag(BaseModel):
    name            = models.CharField(max_length=255, unique=True)
    created_by      = models.ForeignKey(User, related_name='created_tags')
    created_at      = models.DateTimeField(default=datetime.datetime.now, blank=True, null=True)
    marked_by       = models.ManyToManyField(User, related_name="marked_tags", through="MarkedTag")
    # Denormalised data
    used_count = models.PositiveIntegerField(default=0)

    active = ActiveTagManager()

    class Meta:
        ordering = ('-used_count', 'name')
        app_label = 'forum'

    def __unicode__(self):
        return u'%s' % self.name

    def add_to_usage_count(self, value):
        if self.used_count + value < 0:
            self.used_count = 0
        else:
            self.used_count = models.F('used_count') + value

    @models.permalink
    def get_absolute_url(self):
        return ('tag_questions', (), {'tag': self.name})

class MarkedTag(models.Model):
    TAG_MARK_REASONS = (('good', _('interesting')), ('bad', _('ignored')))
    tag = models.ForeignKey(Tag, related_name='user_selections')
    user = models.ForeignKey(User, related_name='tag_selections')
    reason = models.CharField(max_length=16, choices=TAG_MARK_REASONS)

    class Meta:
        app_label = 'forum'

src/forum/forms/admin.py
import socket
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.admin.widgets import FilteredSelectMultiple, AdminDateWidget
from qanda import TitleField, EditorField
from forum import settings
from forum.models.node import NodeMetaClass
from forum.models import User

class IPListField(forms.CharField):
    def clean(self, value):
        ips = [ip.strip() for ip in value.strip().strip(',').split(',')]
        iplist = []

        if len(ips) < 1:
            raise forms.ValidationError(_('Please input at least one ip address'))

        for ip in ips:
            try:
                socket.inet_aton(ip)
            except socket.error:
                raise forms.ValidationError(_('Invalid ip address: %s' % ip))

            if not len(ip.split('.')) == 4:
                raise forms.ValidationError(_('Please use the dotted quad notation for the ip addresses'))

            iplist.append(ip)

        return iplist

class MaintenanceModeForm(forms.Form):
    ips = IPListField(label=_('Allow ips'),
                      help_text=_('Comma separated list of ips allowed to access the site while in maintenance'),
                      required=True,
                      widget=forms.TextInput(attrs={'class': 'longstring'}))

    message = forms.CharField(label=_('Message'),
                              help_text=_('A message to display to your site visitors while in maintainance mode'),
                              widget=forms.Textarea)


TEMPLATE_CHOICES = (
('default', _('Default')),
('sidebar', _('Default with sidebar')),
('none', _('None')),
)

RENDER_CHOICES = (
('markdown', _('Markdown')),
('html', _('HTML')),
('escape', _('Escaped'))
)

class UrlFieldWidget(forms.TextInput):
    def render(self, name, value, attrs=None):
        if not value:
            value = ''

        return """
                <input class="url_field" type="text" name="%(name)s" value="%(value)s" />
                <a class="url_field_anchor" target="_blank" href="%(app_url)s"></a>
            """  % {'name': name, 'value': value, 'app_url': settings.APP_URL}


class PageForm(forms.Form):
    def __init__(self, page, *args, **kwargs):
        if page:
            initial = page.extra
            initial.update(dict(title=page.title, content=page.body))
            super(PageForm, self).__init__(initial=initial, *args, **kwargs)
        else:
            super(PageForm, self).__init__(*args, **kwargs)


    title  = forms.CharField(label=_('Title'), max_length=255, widget=forms.TextInput(attrs={'class': 'longstring'}),
                             initial='New page')
    path  = forms.CharField(label=_('Page URL'), widget=UrlFieldWidget, initial='pages/new/')

    content = forms.CharField(label=_('Page Content'), widget=forms.Textarea(attrs={'rows': 30}))
    mimetype = forms.CharField(label=_('Mime Type'), initial='text/html')

    render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                               label=_('Render Mode'))

    template = forms.ChoiceField(widget=forms.RadioSelect, choices=TEMPLATE_CHOICES, initial='default',
                                 label=_('Template'))
    sidebar = forms.CharField(label=_('Sidebar Content'), widget=forms.Textarea(attrs={'rows': 20}), required=False)
    sidebar_wrap = forms.BooleanField(label=_("Wrap sidebar block"), initial=True, required=False)
    sidebar_render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                                       label=_('Sidebar Render Mode'))

    comments = forms.BooleanField(label=_("Allow comments"), initial=False, required=False)

from forum.forms.auth import SimpleRegistrationForm
from forum.forms.general import SetPasswordForm


class CreateUserForm(SimpleRegistrationForm, SetPasswordForm):
    validate_email = forms.BooleanField(required=False, label=_('send validation email'))

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['username', 'email', 'validate_email', 'password1', 'password2']
        self.fields['email'].label = _('email address')


    

src/forum/forms/qanda.py
import re
from datetime import date
from django import forms
from forum.models import *
from django.utils.translation import ugettext as _
from django.contrib.humanize.templatetags.humanize import apnumber

from django.utils.safestring import mark_safe
from general import NextUrlField, UserNameField, SetPasswordForm
from forum import settings

from forum.modules import call_all_handlers

import logging

class TitleField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(TitleField, self).__init__(*args, **kwargs)
        self.required = True
        self.max_length = 255
        self.widget = forms.TextInput(attrs={'size' : 70, 'autocomplete' : 'off', 'maxlength' : self.max_length})
        self.label  = _('title')
        self.help_text = _('please enter a descriptive title for your question')
        self.initial = ''

    def clean(self, value):
        if len(value) < settings.FORM_MIN_QUESTION_TITLE:
            raise forms.ValidationError(_('title must be must be at least %s characters') % settings.FORM_MIN_QUESTION_TITLE)

        return value

class EditorField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(EditorField, self).__init__(*args, **kwargs)
        self.widget = forms.Textarea(attrs={'id':'editor'})
        self.label  = _('content')
        self.help_text = u''
        self.initial = ''


class QuestionEditorField(EditorField):
    def __init__(self, *args, **kwargs):
        super(QuestionEditorField, self).__init__(*args, **kwargs)
        self.required = not bool(settings.FORM_EMPTY_QUESTION_BODY)


    def clean(self, value):
        if not bool(settings.FORM_EMPTY_QUESTION_BODY) and (len(re.sub('[ ]{2,}', ' ', value)) < settings.FORM_MIN_QUESTION_BODY):
            raise forms.ValidationError(_('question content must be at least %s characters') % settings.FORM_MIN_QUESTION_BODY)

        return value

class AnswerEditorField(EditorField):
    def __init__(self, *args, **kwargs):
        super(AnswerEditorField, self).__init__(*args, **kwargs)
        self.required = True

    def clean(self, value):
        if len(re.sub('[ ]{2,}', ' ', value)) < settings.FORM_MIN_QUESTION_BODY:
            raise forms.ValidationError(_('answer content must be at least %s characters') % settings.FORM_MIN_QUESTION_BODY)

        return value


class TagNamesField(forms.CharField):
    def __init__(self, user=None, *args, **kwargs):
        super(TagNamesField, self).__init__(*args, **kwargs)
        self.required = True
        self.widget = forms.TextInput(attrs={'size' : 50, 'autocomplete' : 'off'})
        self.max_length = 255
        self.label  = _('tags')
        #self.help_text = _('please use space to separate tags (this enables autocomplete feature)')
        self.help_text = _('Tags are short keywords, with no spaces within. At least %(min)s and up to %(max)s tags can be used.') % {
            'min': settings.FORM_MIN_NUMBER_OF_TAGS, 'max': settings.FORM_MAX_NUMBER_OF_TAGS    
        }
        self.initial = ''
        self.user = user

    def clean(self, value):
        value = super(TagNamesField, self).clean(value)
        data = value.strip().lower()

        split_re = re.compile(r'[ ,]+')
        list = {}
        for tag in split_re.split(data):
            list[tag] = tag

        if len(list) > settings.FORM_MAX_NUMBER_OF_TAGS or len(list) < settings.FORM_MIN_NUMBER_OF_TAGS:
            raise forms.ValidationError(_('please use between %(min)s and %(max)s tags') % { 'min': settings.FORM_MIN_NUMBER_OF_TAGS, 'max': settings.FORM_MAX_NUMBER_OF_TAGS})

        list_temp = []
        tagname_re = re.compile(r'^[\w+\.-]+$', re.UNICODE)
        for key,tag in list.items():
            if len(tag) > settings.FORM_MAX_LENGTH_OF_TAG or len(tag) < settings.FORM_MIN_LENGTH_OF_TAG:
                raise forms.ValidationError(_('please use between %(min)s and %(max)s characters in you tags') % { 'min': settings.FORM_MIN_LENGTH_OF_TAG, 'max': settings.FORM_MAX_LENGTH_OF_TAG})
            if not tagname_re.match(tag):
                raise forms.ValidationError(_('please use following characters in tags: letters , numbers, and characters \'.-_\''))
            # only keep one same tag
            if tag not in list_temp and len(tag.strip()) > 0:
                list_temp.append(tag)

        if settings.LIMIT_TAG_CREATION and not self.user.can_create_tags():
            existent = Tag.objects.filter(name__in=list_temp).values_list('name', flat=True)

            if len(existent) < len(list_temp):
                unexistent = [n for n in list_temp if not n in existent]
                raise forms.ValidationError(_("You don't have enough reputation to create new tags. The following tags do not exist yet: %s") %
                        ', '.join(unexistent))


        return u' '.join(list_temp)

class WikiField(forms.BooleanField):
    def __init__(self, disabled=False, *args, **kwargs):
        super(WikiField, self).__init__(*args, **kwargs)
        self.required = False
        self.label  = _('community wiki')
        self.help_text = _('if you choose community wiki option, the question and answer do not generate points and name of author will not be shown')
        if disabled:
            self.widget=forms.CheckboxInput(attrs={'disabled': "disabled"})
    def clean(self,value):
        return value

class EmailNotifyField(forms.BooleanField):
    def __init__(self, *args, **kwargs):
        super(EmailNotifyField, self).__init__(*args, **kwargs)
        self.required = False
        self.widget.attrs['class'] = 'nomargin'

class SummaryField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(SummaryField, self).__init__(*args, **kwargs)
        self.required = False
        self.widget = forms.TextInput(attrs={'size' : 50, 'autocomplete' : 'off'})
        self.max_length = 300
        self.label  = _('update summary:')
        self.help_text = _('enter a brief summary of your revision (e.g. fixed spelling, grammar, improved style, this field is optional)')


class FeedbackForm(forms.Form):
    message = forms.CharField(label=_('Your message:'), max_length=800,widget=forms.Textarea(attrs={'cols':60}))
    next = NextUrlField()

    def __init__(self, user, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        if not user.is_authenticated():
            self.fields['name'] = forms.CharField(label=_('Your name:'), required=False)
            self.fields['email'] = forms.EmailField(label=_('Email (not shared with anyone):'), required=True)



class AskForm(forms.Form):
    title  = TitleField()
    text   = QuestionEditorField()

    def __init__(self, data=None, user=None, *args, **kwargs):
        super(AskForm, self).__init__(data, *args, **kwargs)

        self.fields['tags']   = TagNamesField(user)
        
        if int(user.reputation) < settings.CAPTCHA_IF_REP_LESS_THAN and not (user.is_superuser or user.is_staff):
            spam_fields = call_all_handlers('create_anti_spam_field')
            if spam_fields:
                spam_fields = dict(spam_fields)
                for name, field in spam_fields.items():
                    self.fields[name] = field

                self._anti_spam_fields = spam_fields.keys()
            else:
                self._anti_spam_fields = []

        if settings.WIKI_ON:
            self.fields['wiki'] = WikiField()

class AnswerForm(forms.Form):
    text   = AnswerEditorField()
    wiki   = WikiField()

    def __init__(self, data=None, user=None, *args, **kwargs):
        super(AnswerForm, self).__init__(data, *args, **kwargs)
        
        if int(user.reputation) < settings.CAPTCHA_IF_REP_LESS_THAN and not (user.is_superuser or user.is_staff):
            spam_fields = call_all_handlers('create_anti_spam_field')
            if spam_fields:
                spam_fields = dict(spam_fields)
                for name, field in spam_fields.items():
                    self.fields[name] = field

                self._anti_spam_fields = spam_fields.keys()
            else:
                self._anti_spam_fields = []

        if settings.WIKI_ON:
            self.fields['wiki'] = WikiField()

class RetagQuestionForm(forms.Form):
    tags   = TagNamesField()
    # initialize the default values
    def __init__(self, question, *args, **kwargs):
        super(RetagQuestionForm, self).__init__(*args, **kwargs)
        self.fields['tags'].initial = question.tagnames

class RevisionForm(forms.Form):
    """
    Lists revisions of a Question or Answer
    """
    revision = forms.ChoiceField(widget=forms.Select(attrs={'style' : 'width:520px'}))

    def __init__(self, post, *args, **kwargs):
        super(RevisionForm, self).__init__(*args, **kwargs)

        revisions = post.revisions.all().values_list('revision', 'author__username', 'revised_at', 'summary').order_by('-revised_at')

        date_format = '%c'
        self.fields['revision'].choices = [
            (r[0], u'%s - %s (%s) %s' % (r[0], r[1], r[2].strftime(date_format), r[3]))
            for r in revisions]

        self.fields['revision'].initial = post.active_revision.revision

class EditQuestionForm(forms.Form):
    title  = TitleField()
    text   = QuestionEditorField()
    summary = SummaryField()

    def __init__(self, question, user, revision=None, *args, **kwargs):
        super(EditQuestionForm, self).__init__(*args, **kwargs)

        if revision is None:
            revision = question.active_revision

        self.fields['title'].initial = revision.title
        self.fields['text'].initial = revision.body

        self.fields['tags'] = TagNamesField(user)
        self.fields['tags'].initial = revision.tagnames

        if int(user.reputation) < settings.CAPTCHA_IF_REP_LESS_THAN and not (user.is_superuser or user.is_staff):
            spam_fields = call_all_handlers('create_anti_spam_field')
            if spam_fields:
                spam_fields = dict(spam_fields)

src/forum/skins/default/templates/account_settings.html
{% extends "base_content.html" %}
<!-- settings.html -->
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Account functions" %}{% endspaceless %}{% endblock %}
{% block head %}
<style type="text/css" media="screen">
    h4 {font-size:12pt;}
	dt, dd { padding:0 0 0.35em 0; }
	dt { float: left; width: 21ex;  }
	dd { margin-left: 23ex;  }
	
	#settings-options, #settings-intro { padding: 4em 1.5em;}
	#settings-options { min-height: 300px; border-left: 1px solid #333;}
	
	#settings-options h5 { font-weight: bold;}
</style>
{% endblock %}

{% block content %}
<div id="main-bar">
    <h3><strong>{{ request.user.username }} {% trans "Profile" %}</strong></h3>
</div>
<div id="settings-options">
	{% if msg %}
		<p class="error">{{ msg }}</p>
	{% endif %}

	<dl class="list-item">
        <dt>&raquo; <a href="{% url user_changepw %}">{% trans "Change password" %}</a></dt>
        <dd>{% trans "Give your  account a new password." %}</dd>
        {% comment %}
        <dt>&raquo; <a href="{% url user_changeemail %}">{% trans "Change email " %}</a></dt>
        <dd>{% trans "Add or update the email address associated with your account." %}</dd>

        <dt>&raquo; <a href="{% url user_changeopenid %}">{% trans "Change OpenID" %}</a></dt>
        <dd>{% trans "Change openid associated to your account" %}</dd>

        
        <dt>&raquo; <a href="{% url user_delete %}">{% trans "Delete account" %}</a></dt>
        <dd>{% trans "Erase your username and all your data from website" %}</dd>
        {% endcomment %}
	</dl>
</div>
{% endblock %}
<!-- end settings.html -->

src/forum/skins/default/templates/answer_edit_tips.html
<!-- template answer_edit_tips.html -->
{% load i18n general_sidebar_tags %}
<div class="boxC">
    <p class="subtitle darkred">{% trans "answer tips" %}</p>
    <div>
        <ul class="list-item">
            <li> <b>{% trans "please make your answer relevant to this community" %}</b>
            </li>
            <li>
                {% trans  "try to give an answer, rather than engage into a discussion" %}
            </li>
            <li>
                {% trans "please try to provide details" %}
            </li>
            <li>
				{% trans "be clear and concise" %}
            </li>
        </ul>
        <p class='info-box-follow-up-links'>
            <a href="{% url faq %}" target="_blank" title="{% trans "see frequently asked questions" %}">faq &raquo;</a>
        </p>
    </div>
</div>

{% markdown_help %}
<!-- end template answer_edit_tips.html -->

src/forum/skins/default/templates/base.html
{% extends "base_content.html" %}
{% block page_center %}

{% block full_width_banner %}{% endblock %}

<div id="wrapper">
    {% block site_width_banner %}{% endblock %}
    
    <div id="room">
        <div id="CALeft">
            {% block content%}
            {% endblock%}

        </div>
        <div id="CARight">
            {% block sidebar%}
            {% endblock%}

        </div>
        <div id="tail" style="clear:both;">
            {% block tail %}
            {% endblock %}
        </div>
    </div>
    <div class="spacer3"></div>
</div>
{% endblock %}

src/forum/skins/default/templates/email_base.html
{% load extra_filters %}
{% load extra_tags %}
{% load email_tags %}
{% load i18n %}

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <style type="text/css">
            body {
                background: #FFF;
                font-size: 12px;
                line-height: 150%;
                margin: 0;
                padding: 0;
                color: #000;
                font-family: sans-serif;
            }

            #wrapper {
                width: 600px;
                margin: auto;
                padding: 0;
            }

            a img {
                border: none;
            }
        </style>
    </head>
    <body>
        <a href="{% fullurl index %}">
            <img src="cid:logo" title="{% trans "home" %}" alt="{{settings.APP_TITLE}} logo"/>
        </a>
        <br />
        <p>{{ settings.APP_TITLE }}</p>
    <br /><br />
    <div id="wrapper">
            <div id="room">
                <div id="CALeft">
                    {% block content%}
                    {% endblock%}
                </div>
            </div>
            <div class="spacer3"></div>
        </div>
    </body>
</html>

src/forum/skins/default/templates/index.html
{% extends "questions.html" %}
<!-- index.html -->
{% load general_sidebar_tags %}
{% load question_list_tags %}
{% load i18n %}
{% block fulltitle %}{{ settings.APP_TITLE }}{% endblock %}
{% block sidebar %}
    {% if not request.user.is_authenticated %}
        {% if settings.SHOW_WELCOME_BOX %}
            <div class="boxA">
                <h3>{% trans "welcome to " %}{{ settings.APP_SHORT_NAME }}</h3>
                <div class="body">
                  {{ settings.APP_INTRO|safe }}
                  <div class="more"><a href="{% url about %}">{% trans "about" %} </a></div>
                  <div class="more"><a href="{% url faq %}">{% trans "faq" %} </a></div>
                </div>
            </div>
        {% endif %}
    {% endif %}
    {% include "question_list/count.html" %}
    {% sidebar_upper %}
    {% if request.user.is_authenticated %}
        {% tag_selector %}
    {% endif %}
    {% sidebar_lower %}
    {% recent_tags %}
    {% recent_awards %}
{% endblock %}
<!-- index.html -->


src/forum/skins/default/templates/question_edit.html
{% extends "base.html" %}
<!-- question_edit.html -->
{% load i18n %}
{% load extra_tags %}
{% block title %}{% spaceless %}{% trans "Edit question" %}{% endspaceless %}{% endblock %}
{% block forejs %}
        <script type='text/javascript' src='{% media  "/media/js/wmd/showdown.js" %}'></script>
        <script type='text/javascript' src='{% media  "/media/js/wmd/wmd.js" %}'></script>
        <link rel="stylesheet" type="text/css" href="{% media  "/media/js/wmd/wmd.css" %}" />
        <script type="text/javascript">
		//todo move javascript out        
        $().ready(function(){
            $("#nav_questions").attr('className',"on");
            $('#editor').TextAreaResizer();
            

            //toggle preview of editor
            var display = true;
            var txt = "[{% trans "hide preview" %}]";
            $('#pre-collapse').text(txt);
            $('#pre-collapse').bind('click', function(){
                txt = display ? "[{% trans "show preview" %}]" : "[{% trans "hide preview" %}]";
                display = !display;
                $('#previewer').toggle();
                $('#pre-collapse').text(txt);
            });
            
            //Tags autocomplete action
        	$("#id_tags").autocomplete("/matching_tags/", {
        		matchContains: true,
                max: 20,
                multiple: true,
                multipleSeparator: " ",
                highlightItem: true,
                scroll: true,
                scrollHeight: 300,
        		/*formatItem: function(row, i, max) {
        			return row.n + " ("+ row.c +")";
        		},
                formatResult: function(row, i, max){
                    return row.n;
                }*/
                formatItem: function(row, i, max, value) {
                    return row[1] + " (" + row[2] + ")";
                },

                formatResult: function(row, i, max, value){
                    return row[1];
                }
                
            });         

            $('#id_revision').unbind().change(function(){
                $("#select_revision").click();
            });

            init = $("textarea#editor")[0].value;

            title = $("input#id_title")[0].value;
            body = $("textarea#editor")[0].value;
            tag = $("input#id_tags")[0].value;
        });

        function submitClicked(e, f) {
            if(!(browserTester('chrome') || browserTester('safari'))) {
                $("input.submit")[0].disabled=true;
                $("input.submit")[1].disabled=true;
            }
            window.removeEventListener('beforeunload', beforeUnload, true);
            if (f) {
                f.submit();
            }
        }

        function beforeUnload(e) {
            if($("input#id_title")[0].value != title || $("textarea#editor")[0].value != body || $("input#id_tags")[0].value != tag) {
                 return yourWorkWillBeLost(e);
            }
        }
        window.addEventListener('beforeunload', beforeUnload, true);

        var init = "";
        var title = "";
        var body = "";
        var tag = "";
        </script>
{% endblock %}
        
{% block content %}
<div id="main-bar" class="headNormal">
    {% block edittype %}{% trans "Edit question" %}{% endblock %} [<a href="{{ question.get_absolute_url }}">{% trans "back" %}</a>]
</div>
<div id="main-body" class="ask-body">
    <div id="askform">
        <form id="fmedit" action="" method="post" >
            <label for="id_revision" ><strong>{% trans "revision" %}:</strong></label> <br/> 
            {% if revision_form.revision.errors %}{{ revision_form.revision.errors.as_ul }}{% endif %}
            <div style="vertical-align:middle">
            {{ revision_form.revision }} <input type="submit" style="display:none" id="select_revision" name="select_revision" 
											value="{% trans "select revision"%}">
            </div> 
            <div class="form-item">
                <label for="id_title" ><strong>{{ form.title.label_tag }}:</strong></label> <span class="form-error"></span><br/> 
                {{ form.title }} {{ form.title.errors }}  
                <div class="title-desc">
                    {{ form.title.help_text }}
                </div>     
            </div>
            <div class="form-item">
                <div id="wmd-button-bar" class="wmd-panel"></div>
                {{ form.text }}
                <span class="form-error"></span>
                <div class="preview-toggle">
                    <table width="100%">
                        <tr>
                            <td>
                                <span id="pre-collapse" title="{% trans "Toggle the real time Markdown editor preview" %}">{% trans "toggle preview" %}</span>
                            </td>
                            <td style="text-align: right;" id="editor-metrics"></td>
                            {% if settings.WIKI_ON %}
                            <td style="text-align:right;">
                                {{ form.wiki }} <span style="color:#000;cursor:help" title="{{form.wiki.help_text}}">{{ form.wiki.label_tag }} </span>
                            </td>
                            {% endif %}
                        </tr>
                    
                    </table>   
                </div>
                <div id="previewer" class="wmd-preview"></div>
            </div>
            <div class="form-item">
                <strong>{{ form.tags.label_tag }}:</strong> <span class="form-error"></span><br/>
                {{ form.tags }}  {{ form.tags.errors }}
                <div class="title-desc">
                    {{ form.tags.help_text }}
                </div>
            </div>
            <strong>{{ form.summary.label_tag }}</strong> <br/>
            {{ form.summary }}  {{ form.summary.errors }}
            <div class="title-desc">
                {{ form.summary.help_text }}
            </div>
            
            {% if form.recaptcha %}
            <div class="question-captcha" style="float: left">
            	{{ form.recaptcha.errors }}
            	{{ form.recaptcha }}
            </div>
            <div class="clear"></div>
            {% endif %}
            
            <div class="error" ></div>
            <input type="button" value="{% trans "Save edit" %}" class="submit" onclick="submitClicked(event, this.form)" />
            <input type="button" value="{% trans "Cancel" %}" class="submit" onclick="submitClicked(event, null); history.back(-1);" />
        </form>
    </div>
</div>
{% endblock %}

{% block sidebar %}
{% include "question_edit_tips.html" %}
{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end question_edit.html -->